CREATE TABLE [dbo].[Occupant] (
    [OccupantId]                         UNIQUEIDENTIFIER NOT NULL,
    [ContactGroup]                       UNIQUEIDENTIFIER NULL,
    [Name]                               VARCHAR (50)     NULL,
    [Status]                             INT              NULL,
    [Type]                               INT              NULL,
    [OccupantUse]                        INT              NULL,
    [MixedUse]                           INT              NULL,
    [ContentValue]                       DECIMAL (18, 2)  NULL,
    [SecurityType]                       INT              NULL,
    [DoesSecurityCarryKeys]              BIT              NULL,
    [ExtinguisherMonitorCompany]         VARCHAR (50)     NULL,
    [ExtinguisherMonitorCompanyPhone]    VARCHAR (50)     NULL,
    [AlarmsMonitoringCompany]            VARCHAR (50)     NULL,
    [AlarmsMonitoringCompanyPhone]       VARCHAR (50)     NULL,
    [OccupancyClassicfication]           INT              NULL,
    [StandardIndustrialClassification]   INT              NULL,
    [OccupancyLoadRated]                 INT              NULL,
    [ResidentialOccupantsPresent]        BIT              NULL,
    [NumberOfResidentsOrOccupants]       INT              NULL,
    [SpecialNeedsOccupantsPressent]      BIT              NULL,
    [NumberOfOccupantsWithSpecialNeeds]  INT              NULL,
    [OccupancyLoadByHours800To1700]      INT              NULL,
    [OccupancyLoadByHours1700To2300]     INT              NULL,
    [OccupancyLoadByHours2300To800]      INT              NULL,
    [OccupantsNonAmbulatoryOrRestrained] BIT              NULL,
    [HoursOfOperationStart]              TIME (7)         NULL,
    [HoursOfOPerationEnd]                TIME (7)         NULL,
    [OpenToPublicStart]                  TIME (7)         NULL,
    [OpenToPublicEnd]                    TIME (7)         NULL,
    [NumberOfEmployees]                  INT              NULL,
    [EmergencyIncidentPlayPresent]       BIT              NULL,
    [OccupancyPermitRequired]            BIT              NULL,
    [NFPAUseCode]                        INT              NULL,
    [NFPAOccCode]                        INT              NULL,
    [StateOccCode]                       INT              NULL,
    [LocalOccCode]                       INT              NULL,
    [CertificateOfOccupancyIssued]       BIT              NULL,
    [CertificateOfOccupancyDate]         DATE             NULL,
    [PreviousAndPartialCOOIssued]        VARCHAR (255)    NULL,
    [Notes]                              NCHAR (10)       NULL,
    CONSTRAINT [PK_Occupant] PRIMARY KEY CLUSTERED ([OccupantId] ASC)
);



