CREATE TABLE [dbo].[Property] (
    [PropertyId]            UNIQUEIDENTIFIER  NOT NULL,
    [ContactGroupId]        UNIQUEIDENTIFIER  NULL,
    [Type]                  INT               NULL,
    [Status]                INT               NULL,
    [StartDate]             DATE              NULL,
    [EndDate]               DATE              NULL,
    [AddressId]             UNIQUEIDENTIFIER  NULL,
    [Division]              INT               NULL,
    [FireDistrictBatallion] INT               NULL,
    [InspectionDistrict]    INT               NULL,
    [Station]               INT               NULL,
    [CensusTract]           DECIMAL (18, 2)   NULL,
    [PlannningZone]         INT               NULL,
    [ZoneType]              INT               NULL,
    [ParcelId]              NVARCHAR (50)     NULL,
    [TaxMapNumber]          NVARCHAR (50)     NULL,
    [PropertyValue]         DECIMAL (18, 2)   NULL,
    [Notes]                 NVARCHAR (255)    NULL,
    [AddressType]           INT               NOT NULL,
    [NumberOrMilepost]      VARCHAR (50)      NULL,
    [StreetPrefix]          INT               NULL,
    [StreetOrHighway]       VARCHAR (50)      NULL,
    [StreetType]            INT               NULL,
    [StreetSuffix]          INT               NULL,
    [City]                  INT               NULL,
    [State]                 INT               NULL,
    [Zip]                   VARCHAR (10)      NULL,
    [County]                INT               NULL,
    [Latititude]            [sys].[geography] NULL,
    [Longitude]             [sys].[geography] NULL,
    CONSTRAINT [PK_Property] PRIMARY KEY CLUSTERED ([PropertyId] ASC)
);



