CREATE TABLE [dbo].[Tank] (
    [TankId]                        UNIQUEIDENTIFIER NOT NULL,
    [ChemicalId]                    UNIQUEIDENTIFIER NOT NULL,
    [ContainerNumber]               VARCHAR (50)     NULL,
    [Type]                          INT              NULL,
    [Status]                        INT              NULL,
    [LastUpdateDate]                DATE             NULL,
    [Dimensions]                    VARCHAR (50)     NULL,
    [MaterialState]                 INT              NULL,
    [Location]                      VARCHAR (50)     NULL,
    [Manufacturer]                  VARCHAR (50)     NULL,
    [ManufacturerIdNumber]          VARCHAR (50)     NULL,
    [ModelNumber]                   VARCHAR (50)     NULL,
    [SearialNumber]                 VARCHAR (50)     NULL,
    [AboveGround]                   VARCHAR (50)     NULL,
    [Material]                      INT              NULL,
    [Gauge]                         VARCHAR (50)     NULL,
    [ExteriorCoating]               INT              NULL,
    [CoveringType]                  VARCHAR (50)     NULL,
    [CoveringDepth]                 VARCHAR (50)     NULL,
    [ULNumber]                      VARCHAR (50)     NULL,
    [InstalledBy]                   VARCHAR (50)     NULL,
    [DateInstalled]                 DATE             NULL,
    [RemovedBy]                     VARCHAR (50)     NULL,
    [DateRemoved]                   DATE             NULL,
    [FillOpeningSite]               DECIMAL (18, 2)  NULL,
    [ReturnSize]                    DECIMAL (18, 2)  NULL,
    [IsOverFlowProtection]          BIT              NULL,
    [IsVaporRecoverySystem]         BIT              NULL,
    [IsMonitoringWalls]             BIT              NULL,
    [IsPumpingDevice]               BIT              NULL,
    [PumpType]                      INT              NULL,
    [IsLeakDetectionAdvice]         BIT              NULL,
    [LeakDetectionType]             INT              NULL,
    [IsVented]                      BIT              NULL,
    [VentLocation]                  INT              NULL,
    [VentSize]                      INT              NULL,
    [Capacity]                      INT              NULL,
    [TankInteriorLining]            INT              NULL,
    [IsCompatibleWithOtherProudcts] BIT              NULL,
    [CorrosionProtection]           INT              NULL,
    [PipeType]                      INT              NULL,
    [PipeProtection]                INT              NULL,
    [PipeLeakDetection]             VARCHAR (50)     NULL,
    [MonitorType]                   VARCHAR (50)     NULL,
    [IsOverfillPresent]             BIT              NULL,
    [OverfillInstallDate]           DATE             NULL,
    [IsSpillProtectionPresent]      BIT              NULL,
    [OverfillInstalledDate]         DATE             NULL,
    [SpecialContainerFeatures]      VARCHAR (50)     NULL,
    [ApplicationFiled]              DATE             NULL,
    [ApplicationReceived]           DATE             NULL,
    [ApplicationCompletedDate]      DATE             NULL,
    [ApplicationApprovalDate]       DATE             NULL,
    [Notes]                         VARCHAR (255)    NULL,
    CONSTRAINT [PK_Tank] PRIMARY KEY CLUSTERED ([TankId] ASC),
    CONSTRAINT [FK_Tank_Chemical] FOREIGN KEY ([ChemicalId]) REFERENCES [dbo].[Chemical] ([ChemicalID])
);

