CREATE TABLE [dbo].[Chemical] (
    [ChemicalID]                 UNIQUEIDENTIFIER NOT NULL,
    [Chemical]                   UNIQUEIDENTIFIER NULL,
    [MaxUnitsStored]             VARCHAR (50)     NULL,
    [UnitType]                   INT              NULL,
    [AverageStored]              VARCHAR (50)     NULL,
    [ChemicalLocation]           VARCHAR (50)     NULL,
    [StorageType]                VARCHAR (50)     NULL,
    [IsPressureHazard]           BIT              NULL,
    [IsReactiveHazard]           BIT              NULL,
    [IsAcuteHazard]              BIT              NULL,
    [IsChronicHazard]            BIT              NULL,
    [IsMsdsOnSite]               BIT              NULL,
    [MaxDailyAmount]             VARCHAR (50)     NULL,
    [PhysicalState]              INT              NULL,
    [StoragePressure]            VARCHAR (50)     NULL,
    [Temperature]                VARCHAR (50)     NULL,
    [DaysOnSite]                 VARCHAR (50)     NULL,
    [AnnualUsage]                VARCHAR (50)     NULL,
    [SiteSpecificConsiderations] VARCHAR (50)     NULL,
    [Container]                  INT              NULL,
    [NumberOfContaineres]        INT              NULL,
    CONSTRAINT [PK_Chemical] PRIMARY KEY CLUSTERED ([ChemicalID] ASC)
);

