IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE [NAME] = 'Occupant')
BEGIN

CREATE TABLE [dbo].[Occupant] (
    [AlarmsMonitoringCompany]            [NVARCHAR](50)          NULL,
    [AlarmsMonitoringCompanyPhone]       [NVARCHAR](50)          NULL,
    [BuildingId]                         [UNIQUEIDENTIFIER]  NOT NULL,
    [CertificateOfOccupancyDateOfIssue]  [DATE]                  NULL,
    [CertificateOfOccupancyIssued]       [BIT]                   NULL,
    [ContentValue]                       [BIGINT]                NULL,
    [CreatedBy]                          [NVARCHAR](50)      NOT NULL,
    [CreatedDate]                        [DATETIMEOFFSET](7) NOT NULL,
    [DeactivationReason]                 [NVARCHAR](1023)        NULL,
    [DoesSecurityCarryKeys]              [BIT]                   NULL,
    [EndDate]                            [DATE]                  NULL,
    [ExtinguisherMonitorCompany]         [NVARCHAR](50)          NULL,
    [ExtinguisherMonitorCompanyPhone]    [NVARCHAR](50)          NULL,
    [FileName]                           [NVARCHAR](255)         NULL,
    [FireDoorsTypeId]                    [INT]                   NULL,
    [FireLoadId]                         [INT]                   NULL,
    [FireWallsId]                        [INT]                   NULL,
    [HasEmergencyIncidentPlan]           [BIT]                   NULL,
    [HasRestrainedOccupants]             [BIT]                   NULL,
    [Height]                             [INT]                   NULL,
    [HoursOfOperationEnd]                [TIME](7)               NULL,
    [HoursOfOperationStart]              [TIME](7)               NULL,
    [ImageHeight]                        [INT]                   NULL,
    [ImageId]                            [UNIQUEIDENTIFIER]      NULL,
    [ImageWidth]                         [INT]                   NULL,
    [InteriorDoorsTypeId]                [INT]                   NULL,
    [InteriorWallsTypeId]                [INT]                   NULL,
    [IsDeleted]                          [BIT]                   CONSTRAINT [DF_Occupant_IsDeleted] DEFAULT ((0)) NOT NULL,
    [IsOccupancyPermitRequired]          [BIT]                   NULL,
    [Length]                             [INT]                   NULL,
    [Load1700To2300]                     [INT]                   NULL,
    [Load2300To0800]                     [INT]                   NULL,
    [Load0800To1700]                     [INT]                   NULL,
    [LoadRated]                          [INT]                   NULL,
    [LocalOccCodeId]                     [INT]                   NULL,
    [MixedUseId]                         [INT]                   NULL,
    [NFPAOccCodeId]                      [INT]                   NULL,
    [NFPAUseCodeId]                      [INT]                   NULL,
    [NumberOfEmployees]                  [INT]                   NULL,
    [NumberOfOccupantsWithSpecialNeeds]  [INT]                   NULL,
    [NumberOfResidentsOrOccupants]       [INT]                   NULL,
    [OccupancyClassificationId]          [INT]                   NULL,
    [OccupantId]                         [UNIQUEIDENTIFIER]  NOT NULL,
    [OccupantName]                       [NVARCHAR](50)      NOT NULL,
    [OccupantUseId]                      [INT]                   NULL,
    [OpenToPublicEnd]                    [TIME](7)               NULL,
    [OpenToPublicStart]                  [TIME](7)               NULL,    
    [PreviousAndPartialCOIssued]         [NVARCHAR](255)         NULL,
    [PropertyId]                         [UNIQUEIDENTIFIER]  NOT NULL,
    [ResidentialOccupantsPresent]        [BIT]                   NULL,
    [RowVersion]                         [ROWVERSION]        NOT NULL,
    [SecurityTypeId]                     [INT]                   NULL,
		[SideAExits]                         [SMALLINT]              NULL,
    [SideBExits]                         [SMALLINT]              NULL,
    [SideCExits]                         [SMALLINT]              NULL,
    [SideDExits]                         [SMALLINT]              NULL,
    [SpecialNeedsOccupantsPresent]       [BIT]                   NULL,
    [StandardIndustrialClassificationId] [INT]                   NULL,
    [StartDate]                          [DATE]              NOT NULL,
    [StateOccCodeId]                     [INT]                   NULL,
    [StatusId]                           [INT]                   NULL,
    [SuiteNameNumber]                    [NVARCHAR](50)          NULL,
    [SuiteUnitLocation]                  [NVARCHAR](50)          NULL,
    [TotalExits]                         [INT]                   NULL,
    [TotalSquareFootage]                 [INT]                   NULL,
    [TypeId]                             [INT]                   NULL,
    [UpdatedBy]                          [NVARCHAR](50)      NOT NULL,
    [UpdatedDate]                        [DATETIMEOFFSET](7) NOT NULL,
    [Width]                              [INT]                   NULL,
    CONSTRAINT [PK_Occupant] PRIMARY KEY CLUSTERED ([OccupantId] ASC),
    CONSTRAINT [FK_Occupant_Building] FOREIGN KEY ([BuildingId]) REFERENCES [dbo].[Building] ([BuildingId]),
    CONSTRAINT [FK_Occupant_Property] FOREIGN KEY ([PropertyId]) REFERENCES [dbo].[Property] ([PropertyId])
);

CREATE NONCLUSTERED INDEX [IX_Occupant_UniqueOccupantSuiteForBuilding] ON [dbo].[Occupant]([BuildingId] ASC, [OccupantName] ASC, [SuiteUnitLocation] ASC);

END